### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by AkshayM025** [maitrungduc1410/WebRTC-Demo#43]
Hey actually we facing issue when trying to convert the ios swift code to SWIFT UI, so can you help me out on this or create a example on swiftUI IOS

**Comment by maitrungduc1410** [comment]
I not yet have time at the moment to do example with swift ui, but given the same idea, converting from UIKit to SwiftUI shouldn't cost much effort. 

The demo is very simple, all in 2 files: CallViewController vs PeerConnectionClient

The quickest way is just create a SwiftUI screen then directly renders CallViewController: https://sarunw.com/posts/uiviewcontroller-in-swiftui/
