### ISSUE TITLE
Is there a way to send audio to speaker in iOS?

### ISSUE THREAD

**Issue by JJiOS** [maitrungduc1410/WebRTC-Demo#5]
Hi!

I was testing your code sample and I want to send the audio to the speaker, I changed the AVCaptureSession but when I run the app the audio is on the internal microphone, How can I send the audio to the device speaker in iOS?

**Comment by maitrungduc1410** [comment]
You can check out my latest commit for iOS client, in `CallViewController.swift` I added 2 comment sections (Line 86 and 155) to redirect audio stream to Speaker. 

But notice that if you use Speaker it'll sometimes cause Echo sound
